spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/peterith/currency-microservices-config

server:
  port: 8888
